[package]
name = "rust4failures"
description = "Poker library."
version = "0.0.1"
edition = "2024"
rust-version = "1.72.1"
authors = ["electronicpanopticon <gaoler@electronicpanopticon.com>", "Readers"]
license = "MIT OR Apache-2.0"
keywords = ["rust", "book", "poker", "wasm"]

[dependencies]

[dev-dependencies]

[lints.clippy]
pedantic = "warn"
